SUNET/eduid-userdb

- setup.py
- src/eduid_userdb/data_samples.py
- src/eduid_userdb/testing.py
- src/eduid_userdb/user.py
- src/eduid_userdb/userdb.py
This branch has been used as stable since Jenkins has built it as such. The dashboard is also set up to use it and since it only changes tests, it can be merged without side effects.
> Eperez refactor

- setup.py
- src/eduid_userdb/testing.py
Added a non primary mobile to testing to fix regression in the tests in dashboard
> Add non primary mobile to testing

- src/eduid_userdb/__init__.py
- src/eduid_userdb/element.py
- src/eduid_userdb/event.py
- src/eduid_userdb/exceptions.py
- src/eduid_userdb/password.py
- src/eduid_userdb/tests/test_event.py
- src/eduid_userdb/tests/test_tou.py
- src/eduid_userdb/tests/test_user.py
- src/eduid_userdb/tou.py
- src/eduid_userdb/user.py
Add support for tracking users acceptance of ToU in the User objects.
> ToU event logging

- setup.py
- src/eduid_userdb/actions/tou/__init__.py
- src/eduid_userdb/actions/tou/user.py
- src/eduid_userdb/actions/tou/userdb.py
- src/eduid_userdb/exceptions.py
> Eperez actions user

- src/eduid_userdb/userdb.py
forcing old (attributes) collection in userdb was ignored
> forcing old (attributes) collection in userdb was ignored

- src/eduid_userdb/db.py
- src/eduid_userdb/exceptions.py
The idea is to remove pymongo dependencies and imports in apps that depend on userdb -catch userdb exceptions rather than pymongo exceptions).
> raise local exception on mongo connection failure

- setup.py
- src/eduid_userdb/db.py
- src/eduid_userdb/userdb.py
raise_on_missing now defaults to True instead of False
> Added raise_on_missing to all get_user_by functions.

- src/eduid_userdb/actions/db.py
- src/eduid_userdb/actions/tou/user.py
- src/eduid_userdb/tests/test_action.py
- src/eduid_userdb/tests/test_actions_db.py
- src/eduid_userdb/tests/test_tou.py
With this we have 98% coverage for eduid_userdb.actions.action,  eduid_userdb.actions.db, and 100% for eduid_userdb.actions.tou.user
> Eperez test actions

- src/eduid_userdb/actions/tou/user.py
The to_dict object from the generic User was asking for too many attributes
> the minimal ToU user has not so many properties

- src/eduid_userdb/actions/chpass/__init__.py
- src/eduid_userdb/actions/chpass/user.py
- src/eduid_userdb/actions/chpass/userdb.py
- src/eduid_userdb/dashboard/user.py
- src/eduid_userdb/tests/test_password.py
- src/eduid_userdb/tests/test_tou.py
Related to the Password  change actions plugin
> Eperez chpasswd

- src/eduid_userdb/tests/test_user.py
- src/eduid_userdb/user.py
Fixes a bug observed loading a user record in production.
> Un-primary non-verified-phones before promoting verified ones.

- setup.py
- src/eduid_userdb/dashboard/user.py
needed to make letter proofing use new user objects in dashboard
> add DashboardUser add_letter_proofing_data

- src/eduid_userdb/actions/action.py
- src/eduid_userdb/db.py
> Eperez small details

- src/eduid_userdb/dashboard/userdb.py
- src/eduid_userdb/userdb.py
* Save dashboard users in the new format by default
* fix typo
> Eperez personal ms

- setup.py
- src/eduid_userdb/data_samples.py
- src/eduid_userdb/support/models.py
- src/eduid_userdb/tests/test_support_models.py
that no longer have a pending_mail_address that can be evaluated by GenericFilterDict.
> Fixes the lookup of users that have completed signup

- requirements.txt
- src/eduid_userdb/element.py
- src/eduid_userdb/proofing/__init__.py
- src/eduid_userdb/proofing/proofing_element.py
- src/eduid_userdb/proofing/proofing_state.py
- src/eduid_userdb/proofing/proofingdb.py
- src/eduid_userdb/tests/test_proofing_state.py
Email proofing elements and states
> Eperez email ms

- src/eduid_userdb/proofing/proofingdb.py
get email verification by eppn & email
&
remove verificattion
> get verifications by eppn & email, and remove verifications

- .travis.yml
- src/eduid_userdb/element.py
- src/eduid_userdb/event.py
- src/eduid_userdb/mail.py
- src/eduid_userdb/nin.py
- src/eduid_userdb/password.py
- src/eduid_userdb/phone.py
- src/eduid_userdb/proofing/proofing_element.py
- src/eduid_userdb/tests/test_exceptions.py
- src/eduid_userdb/tests/test_phone.py
- src/eduid_userdb/tests/test_userdb.py
- src/eduid_userdb/user.py
- src/eduid_userdb/userdb.py
Switched uses of basestring to six.string_types
Removed previous changes to userdb.get_user_by_phone that broke tests.
> Added config for travis

- src/eduid_userdb/authninfo.py
- src/eduid_userdb/util.py
> Eperez security ms

- src/eduid_userdb/proofing/db.py
> wrong db names

- setup.py
- src/eduid_userdb/logs/__init__.py
- src/eduid_userdb/logs/element.py
- src/eduid_userdb/tests/test_logs.py
> Rename OidcProofing to SeLegProofing

- setup.py
- src/eduid_userdb/userdb.py
Crash due to duplicate key as the user with missing modified_ts was
inserted.
> Do not crash on users missing modified_ts

- setup.py
- src/eduid_userdb/personal_data/__init__.py
- src/eduid_userdb/personal_data/db.py
- src/eduid_userdb/personal_data/user.py
- src/eduid_userdb/security/__init__.py
- src/eduid_userdb/security/db.py
- src/eduid_userdb/security/user.py
- src/eduid_userdb/userdb.py
Private userdb classes for personal_data and security microservices
> Private userdb

- setup.py
- src/eduid_userdb/logs/element.py
- src/eduid_userdb/tests/test_logs.py
Just check truthiness of strings.
> Loosen log element validation requirement

- setup.py
upgrade tests dependencies to work with python 3
> upgrade tests dependencies

- setup.py
- src/eduid_userdb/testing.py
> Eperez mongo testing

- setup.py
- src/eduid_userdb/actions/action.py
- src/eduid_userdb/actions/db.py
- src/eduid_userdb/actions/tou/user.py
- src/eduid_userdb/tests/test_action.py
- src/eduid_userdb/tests/test_actions_db.py
- src/eduid_userdb/tests/test_tou.py
- src/eduid_userdb/user.py
IdP actions now use eppn rather than user_id to identify users
> Eperez eppn comm

- src/eduid_userdb/proofing/db.py
- src/eduid_userdb/proofing/state.py
- src/eduid_userdb/tests/test_proofing.py
For Johan to review and merge at a suitable time
> proofingelements dataclasses

- setup.py
- src/eduid_userdb/idp.py
- src/eduid_userdb/idp/__init__.py
- src/eduid_userdb/idp/db.py
- src/eduid_userdb/idp/user.py
Bring code over from eduid-IdP
> Eperez strip idp

- setup.py
- src/eduid_userdb/security/element.py
this should fix an error observed when a user is resetting the password with an expired phone code.
> Fix recreation of CodeElement from CodeElement

- setup.py
- src/eduid_userdb/testing.py
- src/eduid_userdb/tests/test_actions_db.py
- src/eduid_userdb/tests/test_userdb.py
Reverts SUNET/eduid-userdb#149
> Revert "Eperez refactor testing"

- setup.py
- src/eduid_userdb/deprecation.py
- src/eduid_userdb/reset_password/__init__.py
- src/eduid_userdb/reset_password/db.py
- src/eduid_userdb/reset_password/element.py
- src/eduid_userdb/reset_password/state.py
- src/eduid_userdb/reset_password/user.py
- src/eduid_userdb/security/db.py
- src/eduid_userdb/security/element.py
- src/eduid_userdb/security/state.py
- src/eduid_userdb/tests/test_resetpw.py
* DB classes for the reset password app: User and UserDB, States and StateDB's
* Deprecation for the old classes (used by the security app)
* Tests
> Eperez reset pw

- setup.py
- src/eduid_userdb/credentials/password.py
- src/eduid_userdb/reset_password/state.py
- src/eduid_userdb/tests/test_credentials.py
- src/eduid_userdb/tests/test_user.py
Keep in the db whether the passwords are generated or custom
> Eperez generated passwd

- src/eduid_userdb/admin/__init__.py
- src/eduid_userdb/dashboard/user.py
- src/eduid_userdb/proofing/db.py
- src/eduid_userdb/reset_password/db.py
- src/eduid_userdb/security/db.py
- src/eduid_userdb/tests/test_resetpw.py
> Eperez deprecations

- setup.py
- src/eduid_userdb/reset_password/__init__.py
- src/eduid_userdb/reset_password/state.py
- src/eduid_userdb/testing.py
Fix issues found by `make typecheck_extra`
> Eperez typecheck extra

- setup.py
- src/eduid_userdb/signup/user.py
* Correct default for raise_on_unknown
> Eperez am fix

- src/eduid_userdb/credentials/fido.py
- src/eduid_userdb/credentials/password.py
- src/eduid_userdb/element.py
- src/eduid_userdb/orcid.py
- src/eduid_userdb/proofing/state.py
- src/eduid_userdb/reset_password/element.py
- src/eduid_userdb/security/element.py
- src/eduid_userdb/tests/test_credentials.py
- src/eduid_userdb/tests/test_password.py
- src/eduid_userdb/tests/test_u2f.py
- src/eduid_userdb/tests/test_webauthn.py
Update for the deprecation of direct calls to `Element.__init__`
> Eperez elem init 2

- src/eduid_userdb/fixtures/users.py
- src/eduid_userdb/tests/test_user.py
- src/eduid_userdb/user.py
Primarily ensure there are no changes to the users in the production database when deploying this.
> dataclass improvements

- setup.py
- src/eduid_userdb/db.py
- src/eduid_userdb/element.py
- src/eduid_userdb/reset_password/state.py
- src/eduid_userdb/security/state.py
- src/eduid_userdb/user.py
- src/eduid_userdb/userdb.py
dataclass auto defines `__repr__` so use `__str__` for log friendly output
> Lundberg repr to str
